### ISSUE TITLE
希望有动态磁贴

### ISSUE THREAD

**Issue by KIITTID** [nguaduot/TimelineWallpaper#1]
希望有动态磁贴，希望增加one  app主页推送

**Comment by nguaduot** [comment]
面向 Windows 11 开发，所以注释掉了写好了的磁贴的代码。one app？Android 系统的吗

**Comment by KIITTID** [comment]
> 

那就是磁贴没搞咯。。。韩寒的一个app，文艺装逼的

**Comment by nguaduot** [comment]
感谢分享，后续图源增加one

**Comment by nguaduot** [comment]
新版本3.8已支持图源one
![image](https://tva3.sinaimg.cn/large/007vdiFCgy1h08047flrlj32801e0x6r.jpg)
